trigger:
  branches:
    include:
      - main  # or your actual branch name

pool:
  vmImage: 'windows-latest'

steps:
  - task: BMCTTAutoRun@1
    inputs:
      HCIConnection: 'cw01.bmc.com:16196'
      UserID: $(myUserId)
      Password: $(myPassword)
      TestLocationPath: 'C:\Users\bgarande\git\TEST\Tests\Scenarios'
      CLIInstallationPath: 'C:\WorkbenchCLI'
      Configuration: 'Repo'
      Repository: 'http://vw-dtw-xat-01.adprod.bmc.com:48231'
